// Embedded site data - generated by build_standalone_viewer.py
window.EMBEDDED_SITE_DATA = {
  "sites": [
    {
      "code": "IB034",
      "denominacion": "Fuente Lacorte-El Frontal",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB034",
      "valor_turistico": "3.6",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "42.062050",
      "longitude": "-2.390883",
      "eclipse_visibility": "not_visible",
      "status": "success",
      "cloud_coverage": "36",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.062050,-2.390883?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB034b",
      "denominacion": "La Pe\u00f1a /El Corral de la Pe\u00f1a / Matecasa",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB034b",
      "valor_turistico": "3.5",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "42.060900",
      "longitude": "-2.387136",
      "eclipse_visibility": "not_visible",
      "status": "success",
      "cloud_coverage": "36",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.060900,-2.387136?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB034c",
      "denominacion": "Los Tormos",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB034c",
      "valor_turistico": "3.4",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "42.061857",
      "longitude": "-2.454492",
      "eclipse_visibility": "not_visible",
      "status": "success",
      "cloud_coverage": "36",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.061857,-2.454492?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB034d",
      "denominacion": "San Roque",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB034d",
      "valor_turistico": "3.8",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "42.012898",
      "longitude": "-2.264032",
      "eclipse_visibility": "visible",
      "status": "success",
      "cloud_coverage": "33",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.012898,-2.264032?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB034e",
      "denominacion": "El Salgar de Silas",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB034e",
      "valor_turistico": "3.8",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "41.984620",
      "longitude": "-2.353893",
      "eclipse_visibility": "visible",
      "status": "success",
      "cloud_coverage": "34",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@41.984620,-2.353893?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB034f",
      "denominacion": "Fuentesalvo",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB034f",
      "valor_turistico": "3.8",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "42.052380",
      "longitude": "-2.340318",
      "eclipse_visibility": "visible",
      "status": "success",
      "cloud_coverage": "36",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.052380,-2.340318?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB034g",
      "denominacion": "Miraflores I",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB034g",
      "valor_turistico": "2.8",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "41.929020",
      "longitude": "-2.179579",
      "eclipse_visibility": "visible",
      "status": "success",
      "cloud_coverage": "35",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@41.929020,-2.179579?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB034h",
      "denominacion": "Serrantes",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB034h",
      "valor_turistico": "3.1",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "42.067290",
      "longitude": "-2.367544",
      "eclipse_visibility": "not_visible",
      "status": "success",
      "cloud_coverage": "36",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.067290,-2.367544?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB034i",
      "denominacion": "Valdeg\u00e9n",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB034i",
      "valor_turistico": "3.3",
      "confidencialidad": "Public",
      "route_difficulty": "Medium",
      "latitude": "42.063583",
      "longitude": "-2.349613",
      "eclipse_visibility": "not_visible",
      "status": "success",
      "cloud_coverage": "36",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.063583,-2.349613?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB034j",
      "denominacion": "Valles de Valdelalosa",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB034j",
      "valor_turistico": "3.8",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "41.969953",
      "longitude": "-2.214522",
      "eclipse_visibility": "not_visible",
      "status": "success",
      "cloud_coverage": "35",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@41.969953,-2.214522?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200",
      "denominacion": "Valdet\u00e9, Perosancio y Tajugueras",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200",
      "valor_turistico": "3",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "42.130958",
      "longitude": "-2.159723",
      "eclipse_visibility": "not_visible",
      "status": "success",
      "cloud_coverage": "32",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.130958,-2.159723?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200b",
      "denominacion": "La Magdalena",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200b",
      "valor_turistico": "3.5",
      "confidencialidad": "Public",
      "route_difficulty": "Medium",
      "latitude": "N/A",
      "longitude": "N/A",
      "eclipse_visibility": "no_coordinates",
      "status": "success",
      "cloud_coverage": "",
      "cloud_status": "error",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@N/A,N/A?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200c",
      "denominacion": "Los Cayos A",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200c",
      "valor_turistico": "6",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "42.084398",
      "longitude": "-2.088449",
      "eclipse_visibility": "not_visible",
      "status": "success",
      "cloud_coverage": "32",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.084398,-2.088449?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200d",
      "denominacion": "Los Cayos B",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200d",
      "valor_turistico": "3.1",
      "confidencialidad": "Public",
      "route_difficulty": "Medium",
      "latitude": "42.083378",
      "longitude": "-2.085237",
      "eclipse_visibility": "not_visible",
      "status": "success",
      "cloud_coverage": "32",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.083378,-2.085237?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200e",
      "denominacion": "Los Cayos C",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200e",
      "valor_turistico": "5.1",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "42.083306",
      "longitude": "-2.084852",
      "eclipse_visibility": "unknown",
      "status": "success",
      "cloud_coverage": "32",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.083306,-2.084852?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200f",
      "denominacion": "Los Cayos S",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200f",
      "valor_turistico": "4",
      "confidencialidad": "Public",
      "route_difficulty": "Medium",
      "latitude": "42.081150",
      "longitude": "-2.091261",
      "eclipse_visibility": "not_visible",
      "status": "success",
      "cloud_coverage": "32",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.081150,-2.091261?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200g",
      "denominacion": "Valdemayor",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200g",
      "valor_turistico": "3.4",
      "confidencialidad": "Public",
      "route_difficulty": "Medium",
      "latitude": "42.199732",
      "longitude": "-2.528254",
      "eclipse_visibility": "not_visible",
      "status": "success",
      "cloud_coverage": "37",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.199732,-2.528254?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200h",
      "denominacion": "Virgen del Prado",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200h",
      "valor_turistico": "5",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "41.963535",
      "longitude": "-1.966703",
      "eclipse_visibility": "visible",
      "status": "success",
      "cloud_coverage": "28",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@41.963535,-1.966703?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200i",
      "denominacion": "Valdecevillo",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200i",
      "valor_turistico": "6.3",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "42.135837",
      "longitude": "-2.256116",
      "eclipse_visibility": "not_visible",
      "status": "success",
      "cloud_coverage": "35",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.135837,-2.256116?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200j",
      "denominacion": "Virgen del Campo",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200j",
      "valor_turistico": "6.3",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "42.143737",
      "longitude": "-2.271836",
      "eclipse_visibility": "not_visible",
      "status": "success",
      "cloud_coverage": "35",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.143737,-2.271836?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200k",
      "denominacion": "El Villar-Poyales",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200k",
      "valor_turistico": "5.3",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "42.125790",
      "longitude": "-2.230414",
      "eclipse_visibility": "not_visible",
      "status": "success",
      "cloud_coverage": "35",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.125790,-2.230414?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200l",
      "denominacion": "Pe\u00f1aportillo",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200l",
      "valor_turistico": "5.4",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "42.194942",
      "longitude": "-2.285160",
      "eclipse_visibility": "visible",
      "status": "success",
      "cloud_coverage": "35",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.194942,-2.285160?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200m",
      "denominacion": "La Canal",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200m",
      "valor_turistico": "5.5",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "42.195464",
      "longitude": "-2.283743",
      "eclipse_visibility": "not_visible",
      "status": "success",
      "cloud_coverage": "35",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.195464,-2.283743?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200n",
      "denominacion": "Soto en Cameros 1, 2 y 3",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200n",
      "valor_turistico": "4.9",
      "confidencialidad": "Public",
      "route_difficulty": "Medium",
      "latitude": "42.297744",
      "longitude": "-2.414614",
      "eclipse_visibility": "not_visible",
      "status": "success",
      "cloud_coverage": "38",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.297744,-2.414614?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200o",
      "denominacion": "la Era del Peladillo",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200o",
      "valor_turistico": "5.9",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "42.083328",
      "longitude": "-2.043049",
      "eclipse_visibility": "not_visible",
      "status": "success",
      "cloud_coverage": "32",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.083328,-2.043049?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200p",
      "denominacion": "Las Navillas",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200p",
      "valor_turistico": "3.1",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "42.067068",
      "longitude": "-1.941051",
      "eclipse_visibility": "visible",
      "status": "success",
      "cloud_coverage": "30",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.067068,-1.941051?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200q",
      "denominacion": "La Torre",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200q",
      "valor_turistico": "3.5",
      "confidencialidad": "Public",
      "route_difficulty": "Medium",
      "latitude": "42.075845",
      "longitude": "-2.040422",
      "eclipse_visibility": "not_visible",
      "status": "success",
      "cloud_coverage": "32",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.075845,-2.040422?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200r",
      "denominacion": "Valdebrajes",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200r",
      "valor_turistico": "3.5",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "42.073576",
      "longitude": "-1.973726",
      "eclipse_visibility": "not_visible",
      "status": "success",
      "cloud_coverage": "30",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.073576,-1.973726?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200s",
      "denominacion": "Las Losas",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200s",
      "valor_turistico": "5",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "42.153846",
      "longitude": "-2.279108",
      "eclipse_visibility": "not_visible",
      "status": "success",
      "cloud_coverage": "35",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.153846,-2.279108?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200t",
      "denominacion": "La Senoba",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200t",
      "valor_turistico": "5.8",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "42.130706",
      "longitude": "-2.267609",
      "eclipse_visibility": "visible",
      "status": "success",
      "cloud_coverage": "35",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.130706,-2.267609?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200u",
      "denominacion": "Navalsaz",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200u",
      "valor_turistico": "6",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "42.120794",
      "longitude": "-2.208504",
      "eclipse_visibility": "visible",
      "status": "success",
      "cloud_coverage": "35",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.120794,-2.208504?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB200v",
      "denominacion": "La Pellejera",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB200v",
      "valor_turistico": "5.1",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "42.218676",
      "longitude": "-2.453835",
      "eclipse_visibility": "visible",
      "status": "success",
      "cloud_coverage": "38",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@42.218676,-2.453835?iso=20260812",
      "horizon_status": "not_checked",
      "shademap_status": ""
    },
    {
      "code": "IB207",
      "denominacion": "Yacimientos de dinosaurios del Jur\u00e1sico-Cret\u00e1cico en Galve",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB207",
      "valor_turistico": "2.9",
      "confidencialidad": "Public",
      "route_difficulty": "Medium",
      "latitude": "40.644417",
      "longitude": "-0.869513",
      "eclipse_visibility": "visible",
      "status": "success",
      "cloud_coverage": "20",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@40.644417,-0.869513?iso=20260812",
      "horizon_status": "not_found",
      "shademap_status": ""
    },
    {
      "code": "IB208",
      "denominacion": "Yacimiento de dinosaurios del Cret\u00e1cico inferior de Vallivana (Morella)",
      "url": "https://info.igme.es/ielig/LIGInfo.aspx?codigo=IB208",
      "valor_turistico": "3",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "40.544161",
      "longitude": "0.031853",
      "eclipse_visibility": "visible",
      "status": "success",
      "cloud_coverage": "26",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@40.544161,0.031853?iso=20260812",
      "horizon_status": "success",
      "shademap_status": ""
    },
    {
      "code": "T0001",
      "denominacion": "Las Cerradicas",
      "url": "N/A",
      "valor_turistico": "5",
      "confidencialidad": "Public",
      "route_difficulty": "Low",
      "latitude": "40.66331",
      "longitude": "-0.87729",
      "eclipse_visibility": "not_visible",
      "status": "success",
      "cloud_coverage": "20",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@40.66331,-0.87729?iso=20260812",
      "horizon_status": "success",
      "shademap_status": "success"
    },
    {
      "code": "T0002",
      "denominacion": "Ababuj Tracksite",
      "url": "N/A",
      "valor_turistico": "5",
      "confidencialidad": "N/A",
      "route_difficulty": "low",
      "latitude": "40.5646",
      "longitude": "-0.8024",
      "eclipse_visibility": "not_visible",
      "status": "manual",
      "cloud_coverage": "19",
      "cloud_status": "success",
      "cloud_url": "https://www.timeanddate.com/eclipse/in/@40.5646,-0.8024?iso=20260812",
      "horizon_status": "success",
      "shademap_status": "success"
    }
  ],
  "siteImages": {
    "IB034": [
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034/fotos/f-ib034-01_web.jpg",
        "alt": "El Frontal",
        "hash": "a922c2044fddb6c9b364a26865b87265"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034/fotos/f-ib034-02_web.jpg",
        "alt": "El Frontal",
        "hash": "1febcabad2fd854284d68631feabc94d"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034/fotos/f-ib034-03_web.jpg",
        "alt": "El Frontal",
        "hash": "bf9452d3f6ab18a44d01432a18b3d184"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034/fotos/f-ib034-04_web.jpg",
        "alt": "Fuente Lacorte",
        "hash": "ea03d4b1737a2cd35e5f1bb706b3fe9c"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034/fotos/f-ib034-05_web.jpg",
        "alt": "Fuente Lacorte",
        "hash": "a59b65276d69aaeed4b52a47fc9a8546"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034/fotos/f-ib034-06_web.jpg",
        "alt": "Fuente Lacorte",
        "hash": "b22d2bbe203c8c91819410fa0ed2e6b9"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034/fotos/f-ib034-07_web.jpg",
        "alt": "Fuente Lacorte",
        "hash": "5adb6031bf25b999236147cb56b80007"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034/fotos/f-ib034-08_web.jpg",
        "alt": "Fuente Lacorte",
        "hash": "9844d54c526ea37f1b79c923a246fc32"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034/fotos/f-ib034-09_web.jpg",
        "alt": "Fuente Lacorte",
        "hash": "c19b9d730d390368165eef6c08f31bc3"
      }
    ],
    "IB034b": [
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034b/fotos/f-ib034b-01_web.jpg",
        "alt": "Matacasa",
        "hash": "64721c0bfdc9e95fe0eb52f520d59a5d"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034b/fotos/f-ib034b-02_web.jpg",
        "alt": "Matacasa",
        "hash": "d9caea56597049c8c65c27b4c8c51958"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034b/fotos/f-ib034b-03_web.jpg",
        "alt": "Matacasa",
        "hash": "599c31fd438a9f547d5cc0d17209194e"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034b/fotos/f-ib034b-04_web.jpg",
        "alt": "Matacasa",
        "hash": "7ba13467edf96081288c20534962b208"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034b/fotos/f-ib034b-05_web.jpg",
        "alt": "Matacasa",
        "hash": "4d459f6ee423a18260f0c69e088fe603"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034b/fotos/f-ib034b-06_web.jpg",
        "alt": "La Pe\u00f1a",
        "hash": "63ebed469413da57b987343c87738324"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034b/fotos/f-ib034b-07_web.jpg",
        "alt": "El Corral de la Pe\u00f1a",
        "hash": "2d0dbea84d47f2bc4c3129dd4ab095a1"
      }
    ],
    "IB034c": [
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034c/fotos/f-ib034c-01_web.jpg",
        "alt": "Site image",
        "hash": "16f79c70b01dad3d83b371cbd27d5d21"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034c/fotos/f-ib034c-02_web.jpg",
        "alt": "Site image",
        "hash": "b5ac52d92ec860cb5d872a914be97797"
      }
    ],
    "IB034d": [
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034d/fotos/f-ib034d-01_web.jpg",
        "alt": "Site image",
        "hash": "b60599f63fda40054cca25ff9af28ce2"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034d/fotos/f-ib034d-02_web.jpg",
        "alt": "Site image",
        "hash": "3ea5d7ff9b740359a5286ed68cabe00a"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034d/fotos/f-ib034d-03_web.jpg",
        "alt": "Site image",
        "hash": "d4a31e08aeaeec9a41b9242be08aba2d"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034d/fotos/f-ib034d-04_web.jpg",
        "alt": "Site image",
        "hash": "58fced6962969b59ef1e5369f55d1575"
      }
    ],
    "IB034e": [
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034e/fotos/f-ib034e-01_web.jpg",
        "alt": "Site image",
        "hash": "cfb29ea3e6ac5d3834e0b3a625e94fd0"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034e/fotos/f-ib034e-02_web.jpg",
        "alt": "Site image",
        "hash": "2a8cc60d085afa66d8b03b25dbf596ab"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034e/fotos/f-ib034e-03_web.jpg",
        "alt": "Site image",
        "hash": "a39eb81a973e69b3fdc90772378d9cd8"
      }
    ],
    "IB034f": [
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034f/fotos/f-ib034f-01_web.jpg",
        "alt": "Site image",
        "hash": "9d5e064cb679ba78ee3b0e0641aaa6fc"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034f/fotos/f-ib034f-02_web.jpg",
        "alt": "Site image",
        "hash": "8d2833c2b533db7c29ca00c6b6b0d570"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034f/fotos/f-ib034f-03_web.jpg",
        "alt": "Site image",
        "hash": "b9cd047a7a8d9851ea98afa27ff29165"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034f/fotos/f-ib034f-04_web.jpg",
        "alt": "Site image",
        "hash": "b667a0b07778ce9bd556f6caacf1650a"
      }
    ],
    "IB034g": [
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034g/fotos/f-ib034g-01_web.jpg",
        "alt": "Site image",
        "hash": "ba2d2a941ffe800b0fc769243f46a9ff"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034g/fotos/f-ib034g-02_web.jpg",
        "alt": "Site image",
        "hash": "60e4004b4252d586714c4e6a39e0760f"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034g/fotos/f-ib034g-03_web.jpg",
        "alt": "Site image",
        "hash": "fc2814ab451c9d26a1f2cba010dc8861"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib034g/fotos/f-ib034g-04_web.jpg",
        "alt": "Site image",
        "hash": "2b5e1d4b6d1bd321c21011df3058bead"
      }
    ],
    "IB200b": [
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200b/fotos/f-ib200b-04_web.jpg",
        "alt": "Vista desde el sendero GR93 del yacimiento de La Magdalena. A\u00f1o 2021",
        "hash": "93587c457cf0f6616606f99369050850"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200b/fotos/f-ib200b-05_web.jpg",
        "alt": "Estrato con las huellas de iguanodontido de La Magdalena. A\u00f1o 2021",
        "hash": "37eba04f802e346748b37a52a4cfd9b5"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200b/fotos/f-ib200b-01_web.jpg",
        "alt": "Vista general del rastro de La Magdalena (Pr\u00e9jano, La Rioja). ",
        "hash": "9c459b57c1563a775a344628c6db7a55"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200b/fotos/f-ib200b-02_web.jpg",
        "alt": "Fragmento del rastro de La Magdalena mostrando las dos primeras huellas del mismo. N\u00f3tese la rotaci\u00f3n de las mismas, que aparecen dirigidas hacia el interior de la l\u00ednea media del rastro",
        "hash": "cc9db7960a5efd17b899c7dffea46f8d"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200b/fotos/f-ib200b-03_web.jpg",
        "alt": "Icnita n\u00ba 2 del rastro de La Magdalena. La lontigud de la misma es de 60 cm.",
        "hash": "ab5f8287a63577681cb5198ff2600a2a"
      }
    ],
    "IB200c": [
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200c/fotos/f-ib200c-06_web.jpg",
        "alt": "Los Cayos, protecci\u00f3n y techado del yacimiento. A\u00f1o 2021. Foto: J. Vegas",
        "hash": "ff1982a8709a557f1e8e04d7bad45499"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200c/fotos/f-ib200c-07_web.jpg",
        "alt": "Rastro principal del yacimiento de Los Cayos. A\u00f1o 2021. Foto: J. Vegas",
        "hash": "13b1623ead63a0a39699ee94b58511e4"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200c/fotos/f-ib200c-01_web.jpg",
        "alt": "Diversos rastros de ter\u00f3podos se cruzan entre s\u00ed en el yacimiento de Los Cayos A.",
        "hash": "6d40fbc1b8ff601c3422db6f6ca3902e"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200c/fotos/f-ib200c-02_web.jpg",
        "alt": "Un conjunto de rastros paralelos de ter\u00f3podos evidenciando una conducta gregaria en el yacimiento de Los Cayos A.",
        "hash": "7963935ddbcaa0b17d23c97a474cbbcb"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200c/fotos/f-ib200c-03_web.jpg",
        "alt": "Yacimiento de Los Cayos A (Cornago, La Rioja). En su superficie estratigr\u00e1fica se pueden contemplar 36 rastros muy bien preservados de dinosaurios ter\u00f3podos. ",
        "hash": "a8a77cbecdfc0e590dc43d8bf97e504c"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200c/fotos/f-ib200c-04_web.jpg",
        "alt": "Detalle de la protecci\u00f3n de parte del yacimiento. Foto: J. Moratalla",
        "hash": "a00c0f98982486835f36e51be81801b4"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200c/fotos/f-ib200c-05_web.jpg",
        "alt": "Icnitas de Dinosaurio en la localidad de Los Cayos, antes de la intervenci\u00f3n. Cornago. Foto: J. Moratalla",
        "hash": "1a0fcaf897e558fe67541a4194f16a4c"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200c/fotos/f-ib200c-08_web.jpg",
        "alt": "Vista completa del yacimiento de los Cayos A, que incluye la parte protegida y el resto del estrato. Foto: J. Moratalla",
        "hash": "e0c4fd83e0b9d33cb20f9bda1a992b58"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200c/fotos/f-ib200c-09_web.jpg",
        "alt": "Detalle de las icnitas trid\u00e1ctilas y los ripples originados por corrientes en el estrato. Foto: J. Moratalla",
        "hash": "ab9aff5f49cfed855018b8efae2a2959"
      }
    ],
    "IB200d": [
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200d/fotos/f-ib200d-01_web.jpg",
        "alt": "Yacimiento de Los Cayos B (Cornago, La Rioja). Su superficie estratigr\u00e1fica est\u00e1 dividida en varios tramos y dos niveles superpuestos en donde se pueden observar 24 rastros de dinosaurios ter\u00f3podos y un buen n\u00famero de icnitas aisladas.",
        "hash": "cb90b300c1e0d5ca84b72cd6d648c2f5"
      }
    ],
    "IB200e": [
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200e/fotos/f-ib200e-01_web.jpg",
        "alt": "Rastros del yacimiento de Los Cayos C",
        "hash": "165cf201e8427e83e80283a65c3300c4"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200e/fotos/f-ib200e-02_web.jpg",
        "alt": "Rastros del yacimiento de Los Cayos C",
        "hash": "d2776faf79166627c3f38657c54bd230"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200e/fotos/f-ib200e-03_web.jpg",
        "alt": "Huella del yacimiento de Los Cayos C",
        "hash": "b4dfc7da11a31177689cbaf95c665c7e"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200e/fotos/f-ib200e-04_web.jpg",
        "alt": "Huellas interpretadas como de tortuga. Los Cayos C",
        "hash": "42a931b2ebb28aa4873a23d49674d520"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200e/fotos/f-ib200e-05.png",
        "alt": "Huellas de quelonios. Yacimiento de Los Cayos C. Foto: J. Moratalla",
        "hash": "5f1632e5713c259a6f6e472d49a068ce"
      }
    ],
    "IB200f": [
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200f/fotos/f-ib200f-01_web.jpg",
        "alt": "Vista general del yacimiento de Los Cayos S",
        "hash": "a50839244e66982ba8ff816954476f4d"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200f/fotos/f-ib200f-02_web.jpg",
        "alt": "Uno de los rastros de Los Cayos S",
        "hash": "bdef632dbc92970ca0d424ca32f80a8a"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200f/fotos/f-ib200f-03_web.jpg",
        "alt": "Detalle de una huella de Los Cayos S",
        "hash": "3d2877fb481b12a75e0a3459b46e9b1f"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200f/fotos/f-ib200f-04_web.jpg",
        "alt": "Rastros en Los Cayos S",
        "hash": "753c80b1e4ba0884d408a317879c5ebf"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200f/fotos/f-ib200f-05_web.jpg",
        "alt": "Unos de los rastros de Los Cayos S",
        "hash": "46151206270b286c1e05dcc5aae858a9"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200f/fotos/f-ib200f-06_web.jpg",
        "alt": "Restos de bivalvos en Los Cayos S",
        "hash": "0803042a3e208cf99e24138ee21ae175"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200f/fotos/f-ib200f-07_web.jpg",
        "alt": "Huella en Los Cayos S",
        "hash": "2995fa4f8ce21185b00644517957428a"
      }
    ],
    "IB200g": [
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200g/fotos/f-ib200g-01_web.jpg",
        "alt": "Yacimiento de Valdemayor (Cabez\u00f3n de Cameros)",
        "hash": "9d199e31445a39960956020b29dd2491"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200g/fotos/f-ib200g-02_web.jpg",
        "alt": "Detalle de las huellas de Iguanodon de Valdemayor (Cabez\u00f3n de Cameros)",
        "hash": "e06a9c82dc595bd5f0675a5931ddd2df"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200g/fotos/f-ib200g-03_web.jpg",
        "alt": "Rastros de Iguanodon de Valdemayor (Cabez\u00f3n de Cameros)",
        "hash": "b141d5ca34e20f095a9fb0d7c28c028c"
      }
    ],
    "IB200k": [
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200k/fotos/f-ib200k-01_web.jpg",
        "alt": "Foto: F. P\u00e9rez Lorente",
        "hash": "f835b91be79f367eb2a4468b82dad0ec"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200k/fotos/f-ib200k-02_web.jpg",
        "alt": "Parte del yacimiento cubierto de El Villar. A\u00f1o 2021. Foto: J. Vegas",
        "hash": "4e8086ea72438f9bf8882ec6cf1a8560"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200k/fotos/f-ib200k-03_web.jpg",
        "alt": "Icnitas que han recibido la denominaci\u00f3n de 'Theroplant\u00edgrada encisensis' de la secci\u00f3n de El Villar. A\u00f1o 2021. Foto: J. Vegas",
        "hash": "16172708a4feab7cb4123b0299d81cb3"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200k/fotos/f-ib200k-04_web.jpg",
        "alt": "Superficie mayor del yacimiento de El Villar-Poyales que contiene hasta 15 rastros. A\u00f1o 2021. Foto: J. Vegas",
        "hash": "862d25f3aa7a463bb6991eec36279180"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200k/fotos/f-ib200k-05_web.jpg",
        "alt": "Detalle de las pisadas del yacimiento de El Villar-Poyales. A\u00f1o 2021. Foto: J. Vegas",
        "hash": "bebf580e3461e004d00007ad3436a139"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200k/fotos/f-ib200k-06_web.jpg",
        "alt": "Detalle de los rastros. A\u00f1o 2021. Foto: J. Vegas",
        "hash": "a7677fe659d3b96b0ccab76ed1c95ee1"
      }
    ],
    "IB200l": [
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200l/fotos/f-ib200l-01_web.jpg",
        "alt": "Foto Patrimonio Paleontol\u00f3gico de La Rioja",
        "hash": "eee05989e24141b60f0acac6aefe70b7"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200l/fotos/f-ib200l-02_web.jpg",
        "alt": "Estrato con icnitas del yacimiento de Pe\u00f1aportillo. A\u00f1o 2021. Foto: J. Vegas",
        "hash": "f14099e788547d12d9b50f4287abdb8c"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200l/fotos/f-ib200l-03_web.jpg",
        "alt": "Yacimiento cubierto de Pe\u00f1aportillo y recreaci\u00f3n de un estegosaurio. A\u00f1o 2021. Foto: J. Vegas",
        "hash": "ce5cc91c7b06693e2bb0d37f2c3022a5"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200l/fotos/f-ib200l-04_web.jpg",
        "alt": "Vista del yacimiento cubierto de Pe\u00f1aportillo desde el yacimiento de La Canal. A\u00f1o 2021. Foto: J. Vegas",
        "hash": "82a75fc2f2e0ed0c7cac88dfea2d9f62"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200l/fotos/f-ib200l-05_web.jpg",
        "alt": "Rastro del yacimiento de Pea\u00f1portillo. A\u00f1o 2021. Foto: J. Vegas",
        "hash": "b03fc59e554073901079dd1f743f6a09"
      }
    ],
    "IB200p": [
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200p/fotos/f-ib200p-01_web.jpg",
        "alt": "Una de las zonas del yacimiento, formada por un estrato calc\u00e1reo con impresiones de icnitas de dinosaurios a techo.",
        "hash": "2069d03ae3c2998e880f23e2ea670760"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200p/fotos/f-ib200p-02_web.jpg",
        "alt": "Algunas icnitas de saur\u00f3podos y de ter\u00f3podos del yacimiento.",
        "hash": "64359aeba7dfa8be4f9a8e7513384a0f"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200p/fotos/f-ib200p-03_web.jpg",
        "alt": "Vista general del yacimiento de icnitas de Las Navillas. A\u00f1o 2021",
        "hash": "045b7b0b7f1a737897514e54cb37506a"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200p/fotos/f-ib200p-04_web.jpg",
        "alt": "Baliza para la se\u00f1alizaci\u00f3n del yacimiento de Las Navillas. A\u00f1o 2021",
        "hash": "06aff721d4d1a01be2881f80f296e00c"
      }
    ],
    "IB200t": [
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200t/fotos/f-ib200t-01_web.jpg",
        "alt": "Estrato del yacimiento de icnitas de La Senoba. A\u00f1o 2021",
        "hash": "2e80cca8997a77f94ffed5aef06aa7ea"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200t/fotos/f-ib200t-02_web.jpg",
        "alt": "Paneles y acondicionamiento del yacimiento de La Senoba. A\u00f1o 2021",
        "hash": "97572cd9d2a9f33e0d14660a2203e0c7"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib200t/fotos/f-ib200t-03_web.jpg",
        "alt": "\u00c1rea recreativa de La Senoba. A\u00f1o 2021",
        "hash": "0bba8c785ae2824ab5746494e492c9af"
      }
    ],
    "IB207": [
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib207/fotos/f-ib207-01_web.jpg",
        "alt": "Huellas de saur\u00f3podos en el Barranco Luca. Foto P\u00e9rez Lorente",
        "hash": "0e535c5d016a1b6f93ec51fa1be7e4cd"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib207/fotos/f-ib207-02_web.jpg",
        "alt": "Las Cerradicas",
        "hash": "e87377151679eaead3f1e40e879eaf6e"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib207/fotos/f-ib207-03_web.jpg",
        "alt": "Las Cerradicas",
        "hash": "9b3bca2745c6c3e6aced306e5be80113"
      }
    ],
    "IB208": [
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib208/fotos/f-ib208-01_web.jpg",
        "alt": "Yacimiento de Vallivana (Morella, Castell\u00f3n) formado por un conjunto de icnitas de ter\u00f3podos de media talla. ",
        "hash": "3265abb9abb5a39a4fcfc37d2351df69"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib208/fotos/f-ib208-02_web.jpg",
        "alt": "Vista de uno de los rastros.",
        "hash": "8e7266af9ac8be8369525ddc8f3f1fea"
      },
      {
        "src": "https://info.igme.es/ielig/documentacion/ib/ib208/fotos/f-ib208-03_web.jpg",
        "alt": "Icnita aislada mostrando la morfolog\u00eda que permite identificar al conjunto como producto de dinosaurios ter\u00f3podos.   ",
        "hash": "3130d27c2a2d0ff63be2269a1b2d5d00"
      }
    ]
  }
};
